default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: cfpXXIV_development

test:
  <<: *default
  database: cfpXXIV_test

production:
  <<: *default
  database: cfpXXIV_production
  url: <%= ENV['DATABASE_URL'] %>
